# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-26 23:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20171222_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='name',
            field=models.TextField(default='KraftyCoder'),
        ),
    ]
