# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-11 16:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20180304_2020'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
