# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-15 12:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20180311_2358'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('created',)},
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ('name',)},
        ),
    ]
